name: edsastapps
channels:
  - conda-forge
dependencies:
  - python=3.13
  - netCDF4=1.7.3
  - xarray
  - pyyaml
  - requests
  - xmltodict
  - noaa-coops
  - siphon
  - dataretrieval
  - soupsieve
  - setuptools
  - importlib-metadata