name: apsviz2
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - scipy
  - matplotlib-base
  - pandas
  - netCDF4
  - xarray
  - siphon
  - xarray
  - siphon
  - requests
  - xmltodict
  - scikit-learn
  - pyyaml
  - seaborn
